package com.mycompany.mavenproject1;

import lombok.Setter;

@Setter
public class Ejercicio3 {
    private String cinta;
    
    public boolean estadoS(int posicion){
        if(cinta.length() == posicion) return false;
        if(cinta.charAt(posicion) == '#') return estadoE1(posicion+1);
        
        return false;
    }
    
    public boolean estadoE1(int posicion){
        if(cinta.length() == posicion) return false;
        if(cinta.charAt(posicion) == 'a') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'A') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'G') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '1') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE2(posicion+1);

        return false;
    }
        
    public boolean estadoE2(int posicion){
        if(cinta.length() == posicion) return false;
        if(cinta.charAt(posicion) == 'a') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'A') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'G') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '1') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE3(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE3(posicion+1);

        return false;
    }
    
        
    public boolean estadoE3(int posicion){
        if(cinta.length() == posicion) return false;
        if(cinta.charAt(posicion) == 'a') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'A') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'G') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '1') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE4(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE4(posicion+1);

        return false;
    }
            
    public boolean estadoE4(int posicion){
        if(cinta.length() == posicion) return true;
        
        if(cinta.charAt(posicion) == 'a') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE1E9(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE1E9(posicion+1);
        
        if(cinta.charAt(posicion) == 'A') return estadoE1E8(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE1E8(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE1E8(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE1E8(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE1E8(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE1E8(posicion+1);
        
        if(cinta.charAt(posicion) == 'G') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE1(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE1(posicion+1);

        if(cinta.charAt(posicion) == '1') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE1E7(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE1E7(posicion+1);
        
        return false;
    }
    
    public boolean estadoE1E9(int posicion){
        if(cinta.length() == posicion) return true;
        if(cinta.charAt(posicion) == 'a') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'A') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'G') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '1') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE2(posicion+1);
        
        return false;
    }
    
    public boolean estadoE1E8(int posicion){
        if(cinta.length() == posicion) return true;
        if(cinta.charAt(posicion) == 'a') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'A') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'G') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '1') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE2(posicion+1);

        
        return false;
    }
    
    public boolean estadoE1E7(int posicion){
        if(cinta.length() == posicion) return true;
        if(cinta.charAt(posicion) == 'a') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'b') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'c') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'd') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'e') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'f') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'g') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'h') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'i') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'j') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'k') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'l') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'm') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'n') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'o') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'p') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'r') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 's') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 't') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'u') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'v') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'w') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'x') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'A') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'B') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'C') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'D') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'E') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'F') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'G') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'H') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'I') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'J') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'K') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'L') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'M') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'N') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Ñ') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'O') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'P') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Q') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'R') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'S') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'T') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'U') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'V') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'W') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'X') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Y') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == 'Z') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '1') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '2') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '3') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '4') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '5') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '6') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '7') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '8') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '9') return estadoE2(posicion+1);
        if(cinta.charAt(posicion) == '0') return estadoE2(posicion+1);

        
        return false;
    }
                            
}
